/**
 * Constant values used across several parts of the dashboard.
 */

// A list of keywords passed to social media API's in order
// to query for just COVID-19 related posts.
const COVID_KEYWORDS = [
  'covid',
  'coronavirus',
  'corona',
  'rona',
  'omicron',
  'vaccine',
  'vacunas',
  'vax',
  'vaccinated',
  'vxxed',
  'unvxxed',
  'pandemic',
  'pandemia',
  'masks',
  'n95',
  'quarantine',
  'booster',
  'pcr',
  'antigen',
  'binax',
  'binaxnow',
];

// A dictionary of COVID-19 topics and substrings used
// to classify incoming posts by those topics using post content.
const COVID_TOPICS = {
  'covid-diabetes': [
    'diabet',
    't1d',
    't2d',
    'insulin',
    'blood sugar',
    'a1c',
    'metformin',
    'heart disease',
    'obes',
    'overweight',
  ],
  'testing': [
    ' test',
    'prueba',
    'pcr',
    'antigen',
    'binax',
    'swab',
    'negative',
    'covid result',
  ],
  'vaccines': [
    'vacc',
    'vax',
    'vxx',
    'shot',
    'jab',
    'vacuna',
    'astrazeneca',
    'j&j',
    'johnson & johnson',
    'johnson and johnson',
    'moderna',
    'pfizer',
    'mrna',
    'one and done',
    'oneanddone',
  ],
  'booster': [
    'boost',
    'third dose',
    'third shot',
    '3rd dose',
    '3rd shot',
  ],
  'treatments': [
    'treatment',
    'cure',
    'antiviral',
    'anti-viral',
    'remdesivir',
    'molnupiravir',
    'paxlovid',
    'pill',
    'antibody drug',
    'monoclonal antibod',
    'ivermectin',
  ],
  'long-hauler': [
    'long haul',
    'long-haul',
    'longhaul',
    'long covid',
    'longcovid',
    'long-term',
    'post-acute',
    'post acute',
    'pasc',
  ],
  'variants': [
    'variant',
    'delta',
    'lambda',
    'omicron',
  ],
  'georgia': [
    'georgia',
    ' ga ',
    'atl',
    'fulton',
    'dekalb',
    'cobb',
    'clayton',
    'gwinnett',
    'albany',
    'dougherty',
  ],
}

module.exports = { COVID_KEYWORDS, COVID_TOPICS };